import "dotenv/config";
import { pathToFileURL } from "node:url";
import { realpathSync } from "node:fs";
import { esc } from "./feed.js";
import { makeStore, loadConfig } from "./store.js";
import { resolveRemoteConfig } from "./produce.js";
import type { ObjectStore } from "./storage.js";
import type { AppConfig } from "./types.js";
import type { BookEntry, BookManifest, BookPart } from "./syncBooks.js";

/**
 * 每本书一个独立播客 feed(bookfeed/<id>.xml,itunes:type=serial),
 * 供 Apple Podcasts 等 App 按"一本书=一档节目"订阅收听。
 * 只渲染 books.json 里已有的音频,不产生任何生成成本。
 * pubDate 用固定基准+集数偏移,保证重建后日期稳定、App 不会误报更新。
 */

const BOOKFEED_PREFIX = "bookfeed/";
// 固定基准日期:让第 1 集落在这天,每集 +1 天,与真实生成时间无关
const BASE_MS = Date.UTC(2026, 0, 1);

function buildBookFeedXml(
  entry: BookEntry,
  config: AppConfig,
  publicUrl: (path: string) => string,
  feedUrl: string,
  imageUrl: string,
): string {
  const en = entry.lang === "en";
  const item = (part: BookPart, isIntro: boolean) => {
    const url = publicUrl(part.path);
    const title = isIntro
      ? en ? "Introduction: two hosts on this book" : "导读:两位主播聊聊这本书"
      : en ? `Part ${part.p} of ${entry.totalParts}` : `第 ${part.p}/${entry.totalParts} 集`;
    const desc =
      part.s ||
      (isIntro
        ? en ? `An introduction to "${entry.name}"` : `《${entry.name}》对话导读`
        : en ? `"${entry.name}", part ${part.p}` : `《${entry.name}》第 ${part.p} 集`);
    return `    <item>
      <title>${esc(title)}</title>
      <guid isPermaLink="false">${esc(`book-${entry.id}-${isIntro ? "intro" : part.p}`)}</guid>
      <description>${esc(desc)}</description>
      <pubDate>${new Date(BASE_MS + part.p * 86400000).toUTCString()}</pubDate>
      <enclosure url="${esc(url)}" length="${part.bytes}" type="audio/mpeg"/>
      <itunes:duration>${Math.round(part.bytes / 12000)}</itunes:duration>
      <itunes:episodeType>${isIntro ? "trailer" : "full"}</itunes:episodeType>${isIntro ? "" : `\n      <itunes:episode>${part.p}</itunes:episode>`}
    </item>`;
  };
  const items = [
    ...(entry.intro ? [item(entry.intro, true)] : []),
    ...[...entry.parts].sort((a, b) => a.p - b.p).map((p) => item(p, false)),
  ].join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${esc(entry.name)}</title>
    <description>${esc(
      en
        ? `"${entry.name}" as an AI-narrated audiobook in ${entry.totalParts} parts. Generated by ${config.feed.title}.`
        : `《${entry.name}》AI 有声书,共 ${entry.totalParts} 集。由 ${config.feed.title} 生成。`,
    )}</description>
    <language>${en ? "en" : esc(config.feed.language)}</language>
    <link>${esc(feedUrl)}</link>
    <atom:link href="${esc(feedUrl)}" rel="self" type="application/rss+xml"/>
    <itunes:author>${esc(config.feed.author)}</itunes:author>
    <itunes:explicit>false</itunes:explicit>
    <itunes:type>serial</itunes:type>
    <itunes:category text="Arts"/>
    <itunes:image href="${esc(imageUrl)}"/>
    <image><url>${esc(imageUrl)}</url><title>${esc(entry.name)}</title><link>${esc(feedUrl)}</link></image>
${items}
  </channel>
</rss>
`;
}

/** 为清单里每本书(重)建 bookfeed/<id>.xml,返回 {name, url} 列表 */
export async function publishBookFeeds(
  config: AppConfig,
  storage: ObjectStore,
  manifest: BookManifest,
): Promise<{ name: string; url: string }[]> {
  const out: { name: string; url: string }[] = [];
  const imageUrl = storage.publicUrl("cover.png");
  for (const entry of manifest.books) {
    if (entry.parts.length === 0) continue;
    const path = `${BOOKFEED_PREFIX}${entry.id}.xml`;
    const feedUrl = storage.publicUrl(path);
    const xml = buildBookFeedXml(entry, config, (p) => storage.publicUrl(p), feedUrl, imageUrl);
    await storage.uploadFile(path, Buffer.from(xml), "application/rss+xml; charset=utf-8");
    out.push({ name: entry.name, url: feedUrl });
  }
  if (out.length > 0) {
    console.log(`[bookfeeds] ${out.length} 本书的播客 feed:`);
    for (const f of out) console.log(`[bookfeeds]   ${f.name}: ${f.url}`);
  }
  return out;
}

// `npm run books:feeds` 手动重建全部书籍 feed
if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  (async () => {
    let config = loadConfig();
    const storage = makeStore(config.bucket);
    config = await resolveRemoteConfig(config, storage);
    const manifest = (await storage.loadJson<BookManifest>("books.json")) ?? { books: [] };
    await publishBookFeeds(config, storage, manifest);
  })().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
